//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDoAn.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_GiaoVien()
        {
            this.Tbl_HoiDong = new HashSet<Tbl_HoiDong>();
            this.Tbl_DoAn = new HashSet<Tbl_DoAn>();
        }
    
        public long ID { get; set; }
        public string TenGiaoVien { get; set; }
        public string MaGiaoVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<long> ChuyenNganh_ID { get; set; }
        public string Email { get; set; }
        public string QueQuan { get; set; }
        public string SoDienThoai { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual Tbl_ChuyenNganh Tbl_ChuyenNganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HoiDong> Tbl_HoiDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DoAn> Tbl_DoAn { get; set; }
    }
}
