//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDoAn.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ThamGia
    {
        public long ID { get; set; }
        public Nullable<long> DoAn_ID { get; set; }
        public Nullable<long> SinhVien_ID { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<long> NamBaoVe_ID { get; set; }
    
        public virtual Tbl_DoAn Tbl_DoAn { get; set; }
        public virtual Tbl_NamBaoVe Tbl_NamBaoVe { get; set; }
        public virtual Tbl_SinhVien Tbl_SinhVien { get; set; }
    }
}
