//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDoAn.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DoAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_DoAn()
        {
            this.Tbl_ThamGia = new HashSet<Tbl_ThamGia>();
        }
    
        public long ID { get; set; }
        public string TenDoAn { get; set; }
        public string MaDoAn { get; set; }
        public Nullable<long> ChuyenNganh_ID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string LinkSource { get; set; }
        public string LinkDocument { get; set; }
        public Nullable<long> GiaoVien_ID { get; set; }
        public Nullable<long> HDCham_ID { get; set; }
    
        public virtual Tbl_ChuyenNganh Tbl_ChuyenNganh { get; set; }
        public virtual Tbl_HDCham Tbl_HDCham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ThamGia> Tbl_ThamGia { get; set; }
        public virtual Tbl_GiaoVien Tbl_GiaoVien { get; set; }
    }
}
