//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDoAn.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SinhVien()
        {
            this.Tbl_ThamGia = new HashSet<Tbl_ThamGia>();
        }
    
        public long ID { get; set; }
        public string TenSinhVien { get; set; }
        public string MaSinhVien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<long> ChuyenNganh_ID { get; set; }
        public Nullable<long> Lop_ID { get; set; }
        public Nullable<long> HeDaoTao_ID { get; set; }
        public Nullable<long> NienKhoa_ID { get; set; }
        public string Email { get; set; }
        public string QueQuan { get; set; }
        public string SoDienThoai { get; set; }
    
        public virtual Tbl_ChuyenNganh Tbl_ChuyenNganh { get; set; }
        public virtual Tbl_HeDaoTao Tbl_HeDaoTao { get; set; }
        public virtual Tbl_Lop Tbl_Lop { get; set; }
        public virtual Tbl_NienKhoa Tbl_NienKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ThamGia> Tbl_ThamGia { get; set; }
    }
}
